# -*- coding: utf-8 -*-
"""Banco_de_dados_ReLido_ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11JQIOE4eWEBEQxIu1BPBWs7d90NMP-aW
"""

!pip install psycopg2-binary pandas

import os
os.environ["DATABASE_URL"] = "postgres://avnadmin:AVNS_iYzJhUfHRbmkvuCcJmO@pg-2f14fc74-estudante-46cd.g.aivencloud.com:23892/defaultdb?sslmode=require"
print("DATABASE_URL definida")

import psycopg2
from urllib.parse import urlparse

DATABASE_URL = os.environ.get("DATABASE_URL")
if not DATABASE_URL:
    raise RuntimeError("DATABASE_URL não foi definida direito")

try:
    conn = psycopg2.connect(DATABASE_URL)
    cur = conn.cursor()
    cur.execute("SELECT version();")
    ver = cur.fetchone()
    cur.close()
    conn.close()
    print("Conexão OK. PostgreSQL version:", ver)
except Exception as e:
    raise RuntimeError("Falha ao conectar: ")

import os
import sys
import psycopg2
import psycopg2.extras
import pandas as pd
from typing import Optional
from urllib.parse import urlparse, parse_qs

def get_conn():
    """
    Tenta abrir conexão e fornece mensagem de erro instrutiva caso falhe.
    """
    try:
        conn = psycopg2.connect(DATABASE_URL)
        return conn
    except Exception as e:
        msg = str(e)
        if "could not translate host name" in msg or "Name or service not known" in msg:
            raise RuntimeError(
                "Erro de DNS: o host fornecido na DATABASE_URL não foi resolvido. "
                "Verifique se copiou corretamente o host do Aiven e se não há caracteres extras.\n"
                f"Erro original: {msg}"
            )
        if "could not connect to server" in msg:
            raise RuntimeError(
                "Não foi possível conectar ao servidor. Verifique host, porta, usuário e senha, "
                "além das configurações de firewall/allowlist. Aiven pode exigir SSL.\n"
                f"Erro original: {msg}"
            )
        raise

CREATE_TABLES_SQL = """
CREATE TABLE IF NOT EXISTS Cliente (
    cpf CHAR(11) PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(100),
    senha VARCHAR(100) NOT NULL,
    dataNasc DATE,
    rua VARCHAR(100),
    bairro VARCHAR(100),
    UF CHAR(2),
    tel1 VARCHAR(15),
    tel2 VARCHAR(15)
);

CREATE TABLE IF NOT EXISTS Administrador (
    cpf CHAR(11) PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    senha VARCHAR(100) NOT NULL,
    login VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS SolicitacaoVenda (
    id SERIAL PRIMARY KEY,
    preco_compra NUMERIC(10,2),
    data_solicitacao DATE NOT NULL,
    status VARCHAR(50),
    idCliente CHAR(11) NOT NULL,
    FOREIGN KEY(idCliente) REFERENCES Cliente(cpf) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Obra (
    id SERIAL PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    genero VARCHAR(100),
    edicao INT,
    autor VARCHAR(100),
    idAdministrador CHAR(11) NOT NULL,
    FOREIGN KEY(idAdministrador) REFERENCES Administrador(cpf) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Exemplar (
    id SERIAL PRIMARY KEY,
    valor NUMERIC(10,2) NOT NULL,
    disponibilidade BOOLEAN DEFAULT TRUE,
    stdConservacao VARCHAR(100),
    idObra INT NOT NULL,
    idAdministrador CHAR(11) NOT NULL,
    idSolicitacaoVenda INT,
    FOREIGN KEY(idObra) REFERENCES Obra(id) ON DELETE CASCADE,
    FOREIGN KEY(idAdministrador) REFERENCES Administrador(cpf) ON DELETE CASCADE,
    FOREIGN KEY(idSolicitacaoVenda) REFERENCES SolicitacaoVenda(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS Compra (
    id SERIAL PRIMARY KEY,
    data DATE NOT NULL,
    status_compra VARCHAR(50),
    valor_total NUMERIC(10,2),
    idCliente CHAR(11) NOT NULL,
    FOREIGN KEY(idCliente) REFERENCES Cliente(cpf) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ItemCompra (
    id SERIAL PRIMARY KEY,
    preco_unitario NUMERIC(10,2) NOT NULL,
    idCompra INT NOT NULL,
    idExemplar INT NOT NULL,
    FOREIGN KEY(idCompra) REFERENCES Compra(id) ON DELETE CASCADE,
    FOREIGN KEY(idExemplar) REFERENCES Exemplar(id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS Feedback (
    id SERIAL PRIMARY KEY,
    nota NUMERIC(4,2),
    comentario VARCHAR(255),
    idCompra INT UNIQUE NOT NULL,
    FOREIGN KEY(idCompra) REFERENCES Compra(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Cancelamento (
    id SERIAL PRIMARY KEY,
    data DATE NOT NULL,
    justificativa VARCHAR(255),
    idCompra INT UNIQUE NOT NULL,
    FOREIGN KEY(idCompra) REFERENCES Compra(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Devolucao (
    id SERIAL PRIMARY KEY,
    data DATE NOT NULL,
    justificativa VARCHAR(255),
    idCompra INT UNIQUE NOT NULL,
    FOREIGN KEY(idCompra) REFERENCES Compra(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS SolicitacaoTroca (
    id SERIAL PRIMARY KEY,
    data_solicitacao DATE NOT NULL,
    status VARCHAR(50),
    stdConservacao VARCHAR(100),
    fotos VARCHAR(200),
    idCliente CHAR(11) NOT NULL,
    idExemplarCliente INT NOT NULL,
    idExemplarSolicitado INT NOT NULL,
    FOREIGN KEY(idCliente) REFERENCES Cliente(cpf) ON DELETE CASCADE,
    FOREIGN KEY(idExemplarCliente) REFERENCES Exemplar(id) ON DELETE RESTRICT,
    FOREIGN KEY(idExemplarSolicitado) REFERENCES Exemplar(id) ON DELETE RESTRICT
);
"""

def create_tables():
    conn = get_conn()
    try:
        cur = conn.cursor()
        cur.execute(CREATE_TABLES_SQL)
        conn.commit()
        cur.close()
        print("Tabelas já existem.")
    finally:
        conn.close()

INSERTS_SQL = """
-- Clientes
INSERT INTO Cliente (cpf, nome, email, senha, dataNasc, rua, bairro, UF, tel1, tel2) VALUES
('11111111111', 'Ana Silva', 'ana@email.com', 'senha123', '1990-05-10', 'Rua A', 'Centro', 'SP', '11999990001', '11988880001'),
('22222222222', 'Bruno Souza', 'bruno@email.com', 'senha456', '1985-08-20', 'Rua B', 'Jardim', 'RJ', '21999990002', '21988880002'),
('33333333333', 'Carla Mendes', 'carla@email.com', 'senha789', '1992-03-15', 'Rua C', 'Bairro Alto', 'MG', '31999990003', '31988880003'),
('44444444444', 'Daniel Oliveira', 'daniel@email.com', 'senha321', '1988-12-05', 'Rua D', 'Vila Nova', 'RS', '51999990004', '51988880004'),
('55555555555', 'Eduarda Lima', 'eduarda@email.com', 'senha654', '1995-07-22', 'Rua E', 'Jardim das Flores', 'SP', '11999990005', '11988880005')
ON CONFLICT (cpf) DO NOTHING;

-- Administrador
INSERT INTO Administrador (cpf, nome, senha, login) VALUES
('66666666666', 'Carlos Lima', 'admin123', 'carlosl'),
('77777777777', 'Daniela Costa', 'admin456', 'danic')
ON CONFLICT (cpf) DO NOTHING;

-- Obra
INSERT INTO Obra (nome, genero, edicao, autor, idAdministrador) VALUES
('O Pequeno Príncipe', 'Infantil', 1, 'Antoine de Saint-Exupéry', '66666666666'),
('Dom Casmurro', 'Romance', 2, 'Machado de Assis', '77777777777'),
('Harry Potter', 'Fantasia', 1, 'J.K. Rowling', '66666666666'),
('O Alquimista', 'Filosofia', 3, 'Paulo Coelho', '77777777777'),
('A Arte da Guerra', 'Estratégia', 1, 'Sun Tzu', '66666666666')
ON CONFLICT DO NOTHING;

-- Exemplar
INSERT INTO Exemplar (valor, disponibilidade, stdConservacao, idObra, idAdministrador) VALUES
(50.00, TRUE, 'Bom', 1, '66666666666'),
(70.00, TRUE, 'Muito Bom', 2, '77777777777'),
(60.00, TRUE, 'Excelente', 3, '66666666666'),
(80.00, TRUE, 'Bom', 4, '77777777777'),
(90.00, TRUE, 'Excelente', 5, '66666666666')
ON CONFLICT DO NOTHING;

-- Compra
INSERT INTO Compra (data, status_compra, valor_total, idCliente) VALUES
('2025-12-01', 'Finalizada', 50.00, '11111111111'),
('2025-12-02', 'Finalizada', 70.00, '22222222222'),
('2025-12-03', 'Finalizada', 60.00, '33333333333'),
('2025-12-04', 'Finalizada', 80.00, '44444444444'),
('2025-12-05', 'Finalizada', 90.00, '55555555555')
ON CONFLICT DO NOTHING;

-- ItemCompra
INSERT INTO ItemCompra (preco_unitario, idCompra, idExemplar) VALUES
(50.00, 1, 1),
(70.00, 2, 2),
(60.00, 3, 3),
(80.00, 4, 4),
(90.00, 5, 5);

-- Feedback
INSERT INTO Feedback (nota, comentario, idCompra) VALUES
(4.5, 'Ótimo atendimento!', 1),
(5.0, 'Produto excelente!', 2),
(4.0, 'Bom livro!', 3),
(3.5, 'Satisfatório', 4),
(5.0, 'Adorei!', 5)
ON CONFLICT DO NOTHING;

-- Cancelamento
INSERT INTO Cancelamento (data, justificativa, idCompra) VALUES
('2025-12-02', 'Cliente desistiu', 2),
('2025-12-04', 'Pagamento não autorizado', 4),
('2025-12-05', 'Erro no pedido', 5)
ON CONFLICT DO NOTHING;

-- Devolucao
INSERT INTO Devolucao (data, justificativa, idCompra) VALUES
('2025-12-03', 'Produto com defeito', 3),
('2025-12-04', 'Não atendeu expectativas', 4),
('2025-12-05', 'Troca por outro exemplar', 5)
ON CONFLICT DO NOTHING;

-- SolicitacaoVenda
INSERT INTO SolicitacaoVenda (preco_compra, data_solicitacao, status, idCliente) VALUES
(60.00, '2025-12-01', 'Pendente', '11111111111'),
(65.00, '2025-12-02', 'Aprovada', '22222222222'),
(70.00, '2025-12-03', 'Pendente', '33333333333'),
(75.00, '2025-12-04', 'Aprovada', '44444444444'),
(80.00, '2025-12-05', 'Pendente', '55555555555')
ON CONFLICT DO NOTHING;

-- SolicitacaoTroca
INSERT INTO SolicitacaoTroca (data_solicitacao, status, stdConservacao, fotos, idCliente, idExemplarCliente, idExemplarSolicitado) VALUES
('2025-12-01', 'Pendente', 'Bom', 'foto1.jpg', '11111111111', 1, 2),
('2025-12-02', 'Pendente', 'Muito Bom', 'foto2.jpg', '22222222222', 2, 3),
('2025-12-03', 'Pendente', 'Excelente', 'foto3.jpg', '33333333333', 3, 4),
('2025-12-04', 'Pendente', 'Bom', 'foto4.jpg', '44444444444', 4, 5),
('2025-12-05', 'Pendente', 'Muito Bom', 'foto5.jpg', '55555555555', 5, 1)
ON CONFLICT DO NOTHING;
"""

def load_initial_data():
    conn = get_conn()
    try:
        cur = conn.cursor()
        cur.execute(INSERTS_SQL)
        conn.commit()
        cur.close()
        print("Dados iniciais inseridos (ou já existiam).")
    finally:
        conn.close()

def table_to_df(table_name: str) -> pd.DataFrame:
    conn = get_conn()
    try:
        df = pd.read_sql_query(f"SELECT * FROM {table_name}", conn)
        return df
    finally:
        conn.close()

def create_cliente(cpf: str, nome: str, email: str, senha: str, dataNasc: Optional[str]=None,
                   rua: Optional[str]=None, bairro: Optional[str]=None, UF: Optional[str]=None,
                   tel1: Optional[str]=None, tel2: Optional[str]=None):
    sql = """
    INSERT INTO Cliente (cpf, nome, email, senha, dataNasc, rua, bairro, UF, tel1, tel2)
    VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
    ON CONFLICT (cpf) DO NOTHING;
    """
    conn = get_conn()
    try:
        cur = conn.cursor()
        cur.execute(sql, (cpf,nome,email,senha,dataNasc,rua,bairro,UF,tel1,tel2))
        conn.commit()
        cur.close()
        print("Cliente inserido (ou já existe).")
    finally:
        conn.close()

from IPython.display import display
import pandas as pd

TABLES = ["Cliente","Administrador","SolicitacaoVenda","Obra","Exemplar",
          "Compra","ItemCompra","Feedback","Cancelamento","Devolucao","SolicitacaoTroca"]

def mostrar_todas_tabelas():
    print("Buscando todas as tabelas e mostrando os primeiros registros (head)...")
    for t in TABLES:
        try:
            df = table_to_df(t)
            print(f"\n--- Tabela: {t} (linhas: {len(df)}) ---")
            display(df.head(10))
        except Exception as e:
            print(f"Erro ao obter tabela {t}: {e}")

def executar_consultas_todas():
    consultas = {}
    consultas['top5_obras'] = pd.read_sql_query("""
        SELECT o.nome AS obra, COUNT(ic.id) AS exemplares_vendidos
        FROM Exemplar e
        JOIN Obra o ON e.idObra = o.id
        JOIN ItemCompra ic ON e.id = ic.idExemplar
        GROUP BY o.id, o.nome
        ORDER BY exemplares_vendidos DESC
        LIMIT 5;
    """, get_conn())
    consultas['gasto_por_cliente'] = pd.read_sql_query("""
        SELECT c.nome AS cliente, SUM(ic.preco_unitario) AS total_gasto
        FROM Cliente c
        JOIN Compra co ON c.cpf = co.idCliente
        JOIN ItemCompra ic ON co.id = ic.idCompra
        GROUP BY c.cpf, c.nome
        ORDER BY total_gasto DESC;
    """, get_conn())
    consultas['exemplares_por_genero'] = pd.read_sql_query("""
        SELECT o.genero, COUNT(e.id) AS exemplares_disponiveis
        FROM Exemplar e
        JOIN Obra o ON e.idObra = o.id
        LEFT JOIN ItemCompra ic ON e.id = ic.idExemplar
        WHERE ic.idExemplar IS NULL
        GROUP BY o.genero
        ORDER BY exemplares_disponiveis DESC;
    """, get_conn())
    consultas['media_preco_conservacao'] = pd.read_sql_query("""
        SELECT e.stdConservacao, ROUND(AVG(e.valor),2) AS preco_medio
        FROM Exemplar e
        GROUP BY e.stdConservacao
        ORDER BY preco_medio DESC;
    """, get_conn())
    consultas['compras_canceladas'] = pd.read_sql_query("""
        SELECT co.id AS id_compra, c.nome AS cliente, ca.justificativa, ca.data AS data_cancelamento
        FROM Compra co
        JOIN Cliente c ON co.idCliente = c.cpf
        JOIN Cancelamento ca ON co.id = ca.idCompra
        ORDER BY ca.data;
    """, get_conn())
    consultas['trocas_por_status'] = pd.read_sql_query("""
        SELECT st.status, COUNT(st.id) AS total_solicitacoes
        FROM SolicitacaoTroca st
        GROUP BY st.status
        ORDER BY total_solicitacoes DESC;
    """, get_conn())
    consultas['avaliacao_cliente'] = pd.read_sql_query("""
        SELECT c.nome AS cliente, COUNT(f.id) AS qtd_feedbacks, ROUND(AVG(f.nota),2) AS media_nota
        FROM Feedback f
        JOIN Compra co ON f.idCompra = co.id
        JOIN Cliente c ON co.idCliente = c.cpf
        GROUP BY c.cpf, c.nome
        ORDER BY media_nota DESC;
    """, get_conn())
    consultas['faturamento_autor'] = pd.read_sql_query("""
        SELECT o.autor, SUM(ic.preco_unitario) AS faturamento_total
        FROM Exemplar e
        JOIN Obra o ON e.idObra = o.id
        JOIN ItemCompra ic ON e.id = ic.idExemplar
        GROUP BY o.autor
        ORDER BY faturamento_total DESC;
    """, get_conn())

    return consultas

def mostrar_consultas():
    resultados = executar_consultas_todas()
    for nome, df in resultados.items():
        print(f"\n--- Consulta: {nome} (linhas: {len(df)}) ---")
        display(df.head(10))

def teste_rapido():
    try:
        conn = get_conn()
        cur = conn.cursor()
        cur.execute("SELECT 1;")
        cur.close()
        conn.close()
        print("Teste de conexão: OK")
    except Exception as e:
        print("Teste de conexão: FALHOU ->", e)
        return

    for t in TABLES:
        try:
            df = table_to_df(t)
            print(f"Tabela {t}: encontrada ({len(df)} linhas)")
        except Exception as e:
            print(f"Tabela {t}: ERRO -> {e}")

    resultados = executar_consultas_todas()
    for nome, df in resultados.items():
        print(f"Consulta {nome}: retornou {len(df)} linhas")

print("Célula A carregada. Execute a Célula B para o menu interativo.")



def read_cliente(cpf: str):
    sql = "SELECT * FROM Cliente WHERE cpf = %s"
    conn = get_conn()
    try:
        cur = conn.cursor()
        cur.execute(sql, (cpf,))
        row = cur.fetchone()
        cols = [d[0] for d in cur.description] if cur.description else []
        cur.close()
        if row:
            return dict(zip(cols, row))
        return None
    finally:
        conn.close()

def update_cliente(cpf: str, **fields):
    if not fields:
        print("Nenhum campo informado para atualização.")
        return
    set_clause = ", ".join([f"{k} = %s" for k in fields.keys()])
    sql = f"UPDATE Cliente SET {set_clause} WHERE cpf = %s"
    params = list(fields.values()) + [cpf]
    conn = get_conn()
    try:
        cur = conn.cursor()
        cur.execute(sql, params)
        conn.commit()
        cur.close()
        print("Cliente atualizado.")
    finally:
        conn.close()

def delete_cliente(cpf: str):
    sql = "DELETE FROM Cliente WHERE cpf = %s"
    conn = get_conn()
    try:
        cur = conn.cursor()
        cur.execute(sql, (cpf,))
        conn.commit()
        cur.close()
        print("Cliente deletado (se existia).")
    finally:
        conn.close()

def menu():
    txt = """
--- MENU ReLido (teste) ---
1 - Criar tabelas (create_tables)
2 - Inserir dados iniciais (load_initial_data)
3 - Mostrar todas as tabelas (DataFrames)
4 - Executar/Mostrar consultas (8 consultas do trabalho)
5 - CRUD Cliente (create/read/update/delete)
6 - Rodar teste rápido (teste_rapido)
0 - Sair
"""
    while True:
        print(txt)
        opt = input("Escolha uma opção: ").strip()
        if opt == "0":
            print("Saindo do menu.")
            break
        elif opt == "1":
            try:
                create_tables()
            except Exception as e:
                print("Erro ao criar tabelas:", e)
        elif opt == "2":
            try:
                load_initial_data()
            except Exception as e:
                print("Erro ao inserir dados iniciais:", e)
        elif opt == "3":
            mostrar_todas_tabelas()
        elif opt == "4":
            try:
                mostrar_consultas()
            except Exception as e:
                print("Erro ao executar consultas:", e)
        elif opt == "5":
            print("CRUD Cliente: a=create b=read c=update d=delete")
            sub = input("Escolha: ").strip()
            if sub == "a":
                cpf = input("cpf (11 dígitos): ").strip()
                nome = input("nome: ").strip()
                email = input("email: ").strip()
                senha = input("senha: ").strip()
                dataNasc = input("dataNasc (YYYY-MM-DD) [opcional]: ").strip() or None
                rua = input("rua [opcional]: ").strip() or None
                bairro = input("bairro [opcional]: ").strip() or None
                UF = input("UF [opcional]: ").strip() or None
                tel1 = input("tel1 [opcional]: ").strip() or None
                tel2 = input("tel2 [opcional]: ").strip() or None
                try:
                    create_cliente(cpf, nome, email, senha, dataNasc, rua, bairro, UF, tel1, tel2)
                except Exception as e:
                    print("Erro ao criar cliente:", e)
            elif sub == "b":
                cpf = input("cpf: ").strip()
                try:
                    r = read_cliente(cpf)
                    print(r)
                except Exception as e:
                    print("Erro ao ler cliente:", e)
            elif sub == "c":
                cpf = input("cpf: ").strip()
                field = input("campo a alterar (nome,email,senha,rua,bairro,UF,tel1,tel2,dataNasc): ").strip()
                val = input("novo valor: ").strip()
                try:
                    update_cliente(cpf, **{field: val})
                except Exception as e:
                    print("Erro ao atualizar cliente:", e)
            elif sub == "d":
                cpf = input("cpf: ").strip()
                try:
                    delete_cliente(cpf)
                except Exception as e:
                    print("Erro ao deletar cliente:", e)
            else:
                print("Opção inválida.")
        elif opt == "6":
            teste_rapido()
        else:
            print("Opção inválida.")

print("Para abrir o menu digite: menu_interativo()")
menu()

print("1) Criando tabelas...")
create_tables()
print("2) Inserindo dados iniciais...")
load_initial_data()
print("3) Exibindo primeiras linhas de Cliente e Obra...")
display(table_to_df("Cliente").head())
display(table_to_df("Obra").head())
print("4) Executando consulta Top5 obras mais vendidas...")
df_top5 = pd.read_sql_query("""
    SELECT o.nome AS obra, COUNT(ic.id) AS exemplares_vendidos
    FROM Exemplar e
    JOIN Obra o ON e.idObra = o.id
    JOIN ItemCompra ic ON e.id = ic.idExemplar
    GROUP BY o.id, o.nome
    ORDER BY exemplares_vendidos DESC
    LIMIT 5;
""", get_conn())
display(df_top5)